---
# tasks file for webserver
- name: install nginx
  yum:
    name: nginx
    state: latest
  when: ansible_os_family == 'RedHat'

- name: enable nginx service
  service:
    name: nginx
    enabled: yes

- name: start nginx service
  service:
    name: nginx
    state: started
